#!/bin/zsh

# https://stackoverflow.com/questions/18810483/what-is-the-zsh-equivalent-of-a-bash-script-getting-the-scripts-directory
SCRIPT_PATH="$0:a:h"
echo $SCRIPT_PATH
cd $SCRIPT_PATH
export RBENV_VERSION=3.2.0
ruby catalyst-core
