#!/Users/pascal/.rbenv/shims/ruby

# encoding: UTF-8
require_relative "Libs/loader.rb"

# ------------------------------------------

uuid = ARGV[0]
Blades::setAttribute(uuid, "mikuType", "NxToday")
puts "ok: #{uuid}"
exit

puts Blades::itemOrNull("ceede5bc-9eec-4f56-a613-d82b237ec665")
exit

Blades::items().each{|item|
    next if item["mikuType"] == "NxDeleted"
    puts item["description"]
    if item["parenting-13"] and item["parenting-13"]["parentuuid"].nil? then
        Blades::setAttribute(item["uuid"], "parenting-13", nil)
    end
}

exit

puts BankDerivedData::recoveredAverageHoursPerDayCached("wave-general-fd3c4ac4-1300")

exit

Blades::items().each{|item|
    if item["Sx09"] then
        puts item["description"]
        Blades::setAttribute(item["uuid"], "sx10", item["Sx09"]["count"])
    end
}

exit

puts Blades::mikuType("NxDeleted").size

exit

puts Blades::mikuTypes()

exit

Blades::filepaths_enumerator().each{|filepath|
    #puts "filepath: #{filepath}"
    item = Blades::filepathToItem(filepath)
    next if item["mikuType"] == "NxDeleted"
    if item["mikuType"] == "NxTask" then
        if item["parenting-13"].nil? then
            puts item["description"]
            Blades::setAttribute(item["uuid"], "parenting-13", {
                "parentuuid" => nil,
                "position"   => -rand
            })
        end
    end
}

Blades::mikuType("NxTask").each{|item|
    next item["parenting-13"]
    puts item["description"]
}

exit

class BladesConfig
    # BladesConfig::repository_path()
    def self.repository_path()
        "/Users/pascal/Galaxy/DataHub/Catalyst/data/blades/00"
    end

    # Blades::filepaths_enumerator()
    def self.filepaths_enumerator()
        Enumerator.new do |filepaths|
            Find.find(BladesConfig::repository_path()) do |path|
                if File.file?(path) and path[-14, 14] == ".blade.sqlite3" then
                    filepaths << path
                end
            end
        end
    end

end

Blades::filepaths_enumerator().each{|filepath|
    puts "filepath: #{filepath}"
    item = Blades::filepathToItem(filepath)
    next if item["mikuType"] == "NxDeleted"
    puts item["description"]
    Fsck::fsckItemOrError(item, true)
}
exit
uuid = "d7226421-fddd-41e3-88f1-9e9f3f8eaaf6"
puts "uuid: #{uuid}"
item = Blades::itemOrNull(uuid)
puts item

exit

Blades::filepaths_enumerator().each{|filepath|
    puts "filepath : #{filepath}"
    uuid = Blades::read_uuid_from_file_or_null(filepath)
    puts uuid
    XCache::setFlag("af24d8c8-8abb-4df1-a342-ec9aca1d0b71:#{uuid}", true)
}

exit

Blades::items().each{|item|
    next if item["mikuType"] == "NxDeleted"
    puts item["uuid"]
}

exit

puts Blades::filepaths_enumerator().to_a.size
puts Blades::items().size

exit

Blades::filepaths_enumerator().each{|filepath|
    puts "filepath : #{filepath}"
    uuid = Blades::read_uuid_from_file_or_null(filepath)
    if filepath1 = XCache::getOrNull("88042ba3-c696-4ccd-bc3d-ff79103df19c:#{uuid}") then
        # We have already seen this one
        puts "filepath1: #{filepath1}"
        exit
    end
    XCache::set("88042ba3-c696-4ccd-bc3d-ff79103df19c:#{uuid}", filepath)
}
Blades::filepaths_enumerator().each{|filepath|
    Blades::ensure_content_addressing(filepath)
}
exit


exit

item = Blades::itemOrNull("f3a8d476-c95e-4e72-8831-1517b87458d2")
puts item
puts Parenting::childrenInOrder(item).size
puts Parenting::determineChildrenSetSizeForce(item).size

exit

exit

Blades::filepaths_enumerator().each{|filepath|

    # To speed up further searches, we pick locations mapping as we go,
    # but only once per location

    if !XCache::getFlag("#{BladesConfig::cache_prefix()}:8303974f-1b05-458b-a9c8-98f5e8344a81:#{filepath}") then
        puts "picking up: #{filepath}".yellow
        uuid = Blades::read_uuid_from_file_or_null(filepath)
        XCache::set("#{BladesConfig::cache_prefix()}:4e4d5752-a99a-4ed1-87b0-eb3fccb2b881:#{uuid}", filepath)
        XCache::setFlag("#{BladesConfig::cache_prefix()}:8303974f-1b05-458b-a9c8-98f5e8344a81:#{filepath}", true)
    end
}

Blades::items().each{|item|
    if item["mikuType"] == "Nx27" then
        puts item["description"]
        filepath = Blades::uuidToFilepathOrNull(item["uuid"])
        if filepath.nil? then
            puts "🤔"
            exit
        end

        filepath2 = "/Users/pascal_honore/Galaxy/DataHub/Nyx/data/blades/#{File.basename(filepath)}"
        if !File.exist?(filepath2) then
            FileUtils.mv(filepath, filepath2)
        end

        uuid = item["uuid"]

        # Delete from XCache
        items = XCache::getOrNull("#{BladesConfig::cache_prefix()}:44a38835-4c00-4af9-a3c6-d5340b202831")
        if items then
            items = JSON.parse(items)
            items.delete(uuid)
            XCache::set("#{BladesConfig::cache_prefix()}:44a38835-4c00-4af9-a3c6-d5340b202831", JSON.generate(items))
        end

    end
}
exit

Bank::insertValue("wave-general-fd3c4ac4-1300", Time.new.to_s[0, 10], -318405)

Bank::getRecords("wave-general-fd3c4ac4-1300")
    .sort_by{|record| record["date"] }
    .each{|record|
        puts "recorduuid: #{record["recorduuid"]}; uuid: #{record["id"]}, date: #{record["date"]}, value: #{"%9.2f" % record["value"]}"
    }

puts BankDerivedData::recoveredAverageHoursPerDayCached("wave-general-fd3c4ac4-1300")
exit

Items::items().each{|item|
    puts "(#{item["uuid"]}, #{item["mikuType"]}, #{item["description"]})"
    Blades::commitItem(item)
}

exit

Items::items().each{|item|
    puts "(#{item["uuid"]}, #{item["mikuType"]})"
    Blades::init(item["uuid"], item["mikuType"])
}
exit

#Blades::ensure_canonical_path("/Users/pascal_honore/Desktop/x.jpg")
#Blades::init("uuid", "NxDeleted")
#puts Blades::filepaths_enumerator().to_a
#filepath = Blades::filepaths_enumerator().to_a.first
#puts Blades::read_uuid_from_file_or_null(filepath)
#puts Blades::uuidToFilepathOrNull("uuid")
#puts Blades::itemOrNull("uuid")
Blades::items_enumerator().each{|item|
    puts item
}
exit

puts Parenting::selectParentForMove(nil)

exit

Blades::mikuType("NxProject")
.each{|item|
    puts item["description"]
}

exit

Blades::mikuType("NxTask")
.each{|item|
    next if item["parenting-13"]
    puts item["description"]
    Items::setAttribute(item["uuid"], "parenting-13", {
        "parentuuid" => nil,
        "position"   => rand
    })
}

exit
exit

puts Blades::mikuType("NxToday")
exit

Blades::mikuType("NxTask")
.each{|item|
    next if item["tlname-11"]
    description = item["description"]
    #if description[-5, 5] == ".webp" then # .mkv
        puts item["description"]
    #    Items::setAttribute(item["uuid"], "tlname-11", ".webp")
    #end
}

exit

exit

Blades::mikuType("URL")
.each{|item|
    #next if item["focus-24"]
    #next if item["nx41"].nil?
    #next if item["nx41"]["position"] > 1
    puts item
    Blades::deleteItem(item["uuid"])
    #puts item["nx41"]
}

exit

puts Blades::mikuTypes()
exit

Items::objects().each{|item|
    if item["payload-uuid-1141"] then
        payload = Items::itemOrNull(item["payload-uuid-1141"])
        if payload then
            puts payload
            Items::setAttribute(item["uuid"], "payload-37", payload)
            Items::setAttribute(item["uuid"], "payload-uuid-1141", nil)
            Items::deleteObject(item["payload-uuid-1141"])
        end
    end
}

exit

Blades::mikuType("NxOndate")
.each{|item|
    #next if item["focus-24"]
    #next if item["nx41"].nil?
    #next if item["nx41"]["position"] > 1
    puts item["description"]
    #puts item["nx41"]
    Items::setAttribute(item["uuid"], "focus-24", {
        "type"  => "task:todo-within-a-week",
        "start" => Time.new.to_s
    })
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")
}

exit

puts Focus24::interactivelyDecideFocus()

exit
exit

Blades::mikuType("NxTask")
.each{|item|
    next if item["taskpos-49"]
    puts item["description"]
    Items::setAttribute(item["uuid"], "taskpos-49", rand)
    #Items::setAttribute(item["uuid"], "mikuType", "NxTask")
}

exit

Blades::mikuType("NxHappening")
.each{|item|
    Items::setAttribute(item["uuid"], "taskpos-49", -1 + rand)
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")

}

Blades::mikuType("AbsolutelyToday")
.each{|item|
    Items::setAttribute(item["uuid"], "taskpos-49", -2 + rand)
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")
}

exit

exit

Blades::mikuType("NxInfinity")
.each{|item|
    Items::setAttribute(item["uuid"], "taskpos-49", 10 + 10*rand)
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")

}

exit

#Items::init("0a8ca68f-d931-4110-825c-8fd290ad7853")
Items::setAttribute("0a8ca68f-d931-4110-825c-8fd290ad7853", "mikuType", c)

exit

puts Blades::mikuType("AbsolutelyToday")
exit

Items::deleteObject("0e8c81d2-135e-4eb6-ac7e-1145f7ff1f30")

exit

uuid = "0e8c81d2-135e-4eb6-ac7e-1145f7ff1f30"
item = Items::entryOrNull(uuid)
Operations::editItemJson(item)

exit

puts NxInfinities::listingItems().count
exit

Blades::mikuType("NxSubline")
.each{|item|
    Items::setAttribute(item["uuid"], "mikuType", "NxLine")
}

exit

Blades::mikuType("NxLine")
.each{|item|
    Items::setAttribute(item["uuid"], "nx41", {
        "type"     => "override",
        "position" => item["position-09"]
    })
}

exit

puts Blades::mikuType("Breakdown")
exit

Items::objects().each{|item|
    next if item["payload-uuid-1141"].nil?
    payload = Items::objectOrNull(item["payload-uuid-1141"])
    next if payload.nil?
    next if payload["mikuType"] != "Breakdown"
    puts item
    puts payload
    exit
}

exit

Blades::mikuType("NxSubline")
.each{|item|
    next if item["px36"]
    Items::setAttribute(item["uuid"], "px36", rand)
}

exit

puts Blades::mikuType("NxHappening")

exit

Blades::mikuType("NxIce")
.each{|item|
    Items::setAttribute(item["uuid"], "px36", rand * 1000)
    Items::setAttribute(item["uuid"], "mikuType", "NxInfinity")
}

exit

Blades::mikuType("NxTask")
.each{|item|
    next if item["px36"]
    Items::setAttribute(item["uuid"], "px36", 0)
}

exit

Blades::mikuType("NxProject")
.each{|item|
    puts JSON.pretty_generate(item)
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")
}

exit

exit

Blades::mikuType("NxTask")
.each{|item|
    puts JSON.pretty_generate(item)
    next if item["cx17"].nil?
    project = Items::objectOrNull(item["cx17"]["parentuuid"])
    puts JSON.pretty_generate(project)
    cx18 = {
        "projectuuid" => project["cx18"]["projectuuid"],
        "projectname" => project["cx18"]["projectname"],
        "position"    => item["cx17"]["position"]
    }
    puts JSON.pretty_generate(cx18)
    Items::setAttribute(item["uuid"], "cx18", cx18)
}

exit

exit

Items::objects().each{|item|
    next if item["payload-uuid-1141"].nil?
    payload = Items::objectOrNull(item["payload-uuid-1141"])
    next if payload.nil?
    next if payload["mikuType"] != "Sequence"
    puts JSON.pretty_generate(item)
    puts JSON.pretty_generate(payload)
    Items::objects().each{|i2|
        next if i2["cx17"].nil?
        next if i2["cx17"]["sequenceuuid"] != payload["sequenceuuid"]
        puts JSON.pretty_generate(i2)
        cx17 = {
            "parentuuid" => item["uuid"],
            "position"   => i2["cx17"]["position"]
        }
        puts JSON.pretty_generate(cx17)
        Items::setAttribute(i2["uuid"], "cx17", cx17)
    }
    Items::setAttribute(item["uuid"], "payload-uuid-1141", nil)
    Items::deleteObject(payload["uuid"])
}

exit

Blades::mikuType("NxPolymorph")
.each{|item|
    puts item
}

exit

=begin

TxBehaviour
{
    "btype": "anniversary"
    "startdate"        : YYYY-MM-DD
    "repeatType"       : "weekly" | "monthly" | "yearly"
    "next_celebration" : YYYY-MM-DD , used for difference calculation when we display after the natural celebration time.
}
Anniversary:
    - uuid              : String
    - mikuType          : "Anniversary"
    - unixtime          :
    - datetime          :
    - description       : String
    - startdate"        : YYYY-MM-DD
    - repeatType"       : "weekly" | "monthly" | "yearly"
    - next_celebration" : YYYY-MM-DD , used for difference calculation when we display after the natural celebration time.

=end

Blades::mikuType("NxPolymorph")
.select{|item| item["bx42"]["btype"] == "anniversary"}
.each{|item|
    puts JSON.pretty_generate(item)
    Items::setAttribute(item["uuid"], "startdate", item["bx42"]["startdate"])
    Items::setAttribute(item["uuid"], "repeatType", item["bx42"]["repeatType"])
    Items::setAttribute(item["uuid"], "next_celebration", item["bx42"]["next_celebration"])
    Items::setAttribute(item["uuid"], "mikuType", "Anniversary")
    #i2 = Items::objectOrNull(item["uuid"])
    #puts JSON.pretty_generate(i2)
}

exit

exit

Blades::mikuType("NxLine")
.each{|item|
    next if item["nx41"]
    puts item
    Items::setAttribute(item["uuid"], "nx41", {
        "unixtime" => Time.new.to_f,
        "position" => item["position-09"]
    })
}

exit

Blades::mikuType("NxTask")
.each{|item|
    Items::setAttribute(item["uuid"], "px36", item["px36"])
}

exit

NxProjects::alignLx56()

exit

puts NxProjects::interactivelySelectProjectOrNull()

exit



puts NxTasks::nextOrdinal()
exit

puts Blades::mikuType("NxSequenceItem")

exit

Blades::mikuType("NxTask")
.each{|item|
    Items::setAttribute(item["uuid"], "bx42", nil)
}

exit

=begin
{
    "btype": "task"
    "unixtime": Float
}
NxTask:
    - uuid         : String
    - mikuType     : "NxTask"
    - unixtime     :
    - datetime     :
    - description  : String
    - px36 : Float
=end

cursor = 1

Blades::mikuType("NxPolymorph")
.select{|item| item["bx42"]["btype"] == "task" }
.sort_by{|item| item["bx42"]["unixtime"] }
.each{|item|
    cursor = cursor + 1
    puts JSON.pretty_generate(item)
    Items::setAttribute(item["uuid"], "px36", cursor)
    Items::setAttribute(item["uuid"], "mikuType", "NxTask")
}

exit

puts NxProjects::interactivelyDecidePriority()
exit

=begin
{
    "btype": "task"
    "unixtime": Float
}

NxProject:
    - uuid        : String
    - mikuType    : "NxProject"
    - unixtime    :
    - datetime    :
    - description : String
    - tx20        : NxTimeCommitment
=end

cursor = 1

Blades::mikuType("NxPolymorph")
.select{|item| item["bx42"]["btype"] == "task" }
.sort_by{|item| item["unixtime"] }
.each{|item|
    if item["bx42"]["btype"] == "task" then
        puts JSON.pretty_generate(item)
        puts JSON.pretty_generate(item["bx42"])
        Items::setAttribute(item["uuid"], "tx20", item["bx42"]["timeCommitment"])
        Items::setAttribute(item["uuid"], "mikuType", "NxProject")
    end
}

exit
