name:                catalyst-haskell
version:             0.1.0.0
github:              "shtukas/catalyst"
license:             BSD3
author:              "shtukas"
maintainer:          "pascal@alseyn.net"
copyright:           "2021 shtukas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Haskell implementation of Catalyst

dependencies:
- base >= 4.7 && < 5
- aeson

library:
  source-dirs: src

executables:
  catalyst-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catalyst-haskell

tests:
  catalyst-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catalyst-haskell
